apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  tls:
  - secretName: {{ include "helm.fullname" . }}
    hosts:
    - {{ .Values.ingress.host | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "helm.fullname" . | quote }}
          servicePort: http
