namespace: authgear

mainServer:
  image: __replace_me__

  ingress:
    host: __replace_me__.example.com
    tls:
      secretName: __replace_me__

  env:
    TRUST_PROXY: "true"
    LOG_LEVEL: "warn"
    SENTRY_DSN: ""
    ADMIN_API_AUTH: "jwt"
    CONFIG_SOURCE_TYPE: "kubernetes"
    CONFIG_SOURCE_KUBE_NAMESPACE: "authgear-apps"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

adminServer:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 64Mi

resolverServer:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 64Mi

portalServer:
  image: __replace_me__

  ingress:
    host: __replace_me__.example.com
    tls:
      secretName: __replace_me__

  env:
    TRUST_PROXY: "true"
    LOG_LEVEL: "warn"
    SENTRY_DSN: ""
    CONFIG_SOURCE_TYPE: "kubernetes"
    CONFIG_SOURCE_KUBE_NAMESPACE: "authgear-apps"
    AUTHGEAR_CLIENT_ID: __replace_me__
    AUTHGEAR_ENDPOINT: __replace_me__.example.com
    ADMIN_API_TYPE: "static"
    ADMIN_API_AUTH: "jwt"
    ADMIN_API_ENDPOINT: __replace_me__.example.com
